<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>SpringIOSpringBoot</artifactId>
        <groupId>cn.cc</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sp22-redis</artifactId>
    <packaging>pom</packaging>
    <description>redis功能测试</description>

    <modules>
        <module>sp22-redis-single</module>
        <module>sp22-redis-cluster</module>
    </modules>

</project>