
### 根据停车规则计算金额
POST http://localhost:8083/test/park
Accept: application/json
Content-Type: application/json

{
  "carNum":"豫A123456",
  "carType":1,
  "inTime":1717686061000,
  "outTime":1717819261000,
  "parkId":123,
  "vipLevel":0
}

### 从数据库加载规则
POST http://localhost:8083/test/reloaddb
Accept: application/json
Content-Type: application/json

{
  "ruleId": 3
}

### 从文件加载规则
GET http://localhost:8080/test/reloadfile

### 测试数据库和缓存
GET http://localhost:8082/testdb/result/100

### 缓存
GET http://localhost:8080/actuator/caches
