# MySQL配置
mysql.url=jdbc:mysql://8.146.199.165:3308/ai_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mysql.username=cceverfor
mysql.password=5664c.c.

# Redis配置
redis.host=localhost
redis.port=6379
redis.password=

# Netty配置
netty.port=8080