<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.cc</groupId>
    <artifactId>common-spring-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <description>spring公共模块</description>

    <properties>
        <revision>1.0</revision>
        <common.spring.aop>${revision}</common.spring.aop>
        <common.spring.aop.expiringmap>${revision}</common.spring.aop.expiringmap>
        <common.spring.core>${revision}</common.spring.core>
        <common.spring.fastjson>${revision}</common.spring.fastjson>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.cc</groupId>
                <artifactId>common-spring-aop</artifactId>
                <version>${common.spring.aop}</version>
            </dependency>
            <dependency>
                <groupId>cn.cc</groupId>
                <artifactId>common-spring-aop-expiringmap</artifactId>
                <version>${common.spring.aop.expiringmap}</version>
            </dependency>
            <dependency>
                <groupId>cn.cc</groupId>
                <artifactId>common-spring-core</artifactId>
                <version>${common.spring.core}</version>
            </dependency>
            <dependency>
                <groupId>cn.cc</groupId>
                <artifactId>common-spring-fastjson</artifactId>
                <version>${common.spring.fastjson}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>