<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.cc</groupId>
    <artifactId>common-spring-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <description>spring公共模块</description>

    <properties>
        <revision>1.0</revision>
        <cn.cc.common.spring.core>${revision}</cn.cc.common.spring.core>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.cc</groupId>
                <artifactId>common-spring-core</artifactId>
                <version>${cn.cc.common.spring.core}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>