FROM mysql:8.0

#设置免密登录
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes

#将所需文件放到容器中
#COPY flow.sh /mysql/flow.sh
# 权限
COPY privileges.sql /mysql/privileges.sql
# 备份文件
COPY backup.sql /mysql/backup.sql

#VOLUME ["/var/lib/mysql","/etc/mysql"]
#设置容器启动时执行的命令
#CMD ["sh", "/mysql/flow.sh"]

EXPOSE 3308