server:
  port: 8033
spring:
  rabbitmq:
    host: 8.146.199.165
    port: 5672
    virtual-host: my_vhost # my_vhost # /
    username: c.c.
    password: c.c.c.c.
    listener:
      simple:
        prefetch: 10 # 默认只投递一条，处理完了才能继续下一个