server:
  port: 8031
sysconfig:
  fileRoot: D:/Cache/BaiduNetdiskWorkspace/java/filesystem/project/SpringIOSpringBoot/sp31-user-craw/novel/
  chromedriver: C:/everforcc/java/environment\driver\chromedriver.exe