package drl
import cn.cc.dto.PCarInfo
import cn.cc.service.IRuleService

global cn.cc.service.service.RuleTempOnceDrlImpl ruleTempOnceDrlImpl
global cn.cc.service.service.RuleTempDurationDrlImpl ruleTempDurationDrlImpl
global cn.cc.service.service.RuleVIPFreeDrlImpl ruleVIPFreeDrlImpl
global cn.cc.service.service.RuleVIPMonthDrlImpl ruleVIPMonthDrlImpl

dialect  "java"

rule "特殊车辆"
    when p : PCarInfo(0==carType)
    then
        ruleVIPFreeDrlImpl.dealFee(p);
end

rule "普通车辆"
    when p : PCarInfo(1==carType && 0==vipLevel)
    then
        ruleTempOnceDrlImpl.dealFee(p);
end
