package drl
import cn.cc.dto.PCarInfo
import cn.cc.asyn.service.IRuleService

global cn.cc.asyn.service.service.RuleTempDurationDrlImpl ruleTempDurationDrlImpl
global cn.cc.asyn.service.service.RuleTempOnceDrlImpl ruleTempOnceDrlImpl
global cn.cc.asyn.service.service.RuleTempSectionDrlImpl ruleTempSectionDrlImpl
global cn.cc.asyn.service.service.RuleVIPFreeDrlImpl ruleVIPFreeDrlImpl
global cn.cc.asyn.service.service.RuleVIPMonthDrlImpl ruleVIPMonthDrlImpl
global cn.cc.mvc.Result r

dialect  "java"

rule "特殊车辆"
    when p : PCarInfo(0==carType)
    then
        r.setMsg(ruleVIPFreeDrlImpl.dealFee(p));
end

rule "普通车辆"
    when p : PCarInfo(1==carType && 0==vipLevel)
    then
        r.setMsg(ruleTempOnceDrlImpl.dealFee(p));
end
