server:
  port: 8080

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        connectTimeout: 30000
        socketTimeout: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://8.146.199.165:3308/hkzkcrcc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: cceverfor
          password: 5664c.c.
  redis:
    cluster:
      nodes: 10.250.250.21:5201,10.250.250.21:5202,10.250.250.21:5203,10.250.250.21:5204,10.250.250.21:5205,10.250.250.21:5206
    password: hkzkdev
    timeout: 3000
  cache:
    type: redis
  boot:
    admin:  # 监控地址
      client:
        url: http://localhost:80
  application:
    name: sp41-drools
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 驼峰命名法问题，等效配置文件

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  file: # 监控日志
    name: logs/sp41-drools/info.log
app:
  cache:
    testCache: { name: TEST_CACHE,expire: 30m }
    test:
      name: testname