### 1. 获取小说基本信息 msg
POST http://localhost:31/test/msg
Content-Type: application/json

{
  "url": "https://www.vipxs.la/56_56024/",
  "config":
  {
    "novelMsgTileXR": "//*[@id=\"info\"]/h1//text()",
    "novelMsgDescriptionXR": "//*[@id=\"intro\"]/p//text()",
    "novelMsgAuthXR": "//*[@id=\"info\"]/p[1]//text()",
    "novelCapterUrlListXR": "//*[@id=\"list\"]/dl//a//@href",
    "novelCapterNameXR": "//*[@id=\"wrapper\"]/div[5]/div[1]/div[2]/h1//text()",
    "novelContentXR": "//[@id='content']//text()"
  }
}

### 2. 获取全部目录 menu
POST http://localhost:31/test/menu
Content-Type: application/json

{
  "url": "https://www.vipxs.la/56_56024/",
  "config":
  {
    "novelMsgTileXR": "//*[@id=\"info\"]/h1//text()",
    "novelMsgDescriptionXR": "//*[@id=\"intro\"]/p//text()",
    "novelMsgAuthXR": "//*[@id=\"info\"]/p[1]//text()",
    "novelCapterUrlListXR": "//*[@id=\"list\"]/dl//a//@href",
    "novelCapterNameXR": "//*[@id=\"wrapper\"]/div[5]/div[1]/div[2]/h1//text()",
    "novelContentXR": "//[@id='content']//text()"
  }
}

### 用正则 剔除数据 regex('<h1>(正文)(.*)</h1>', 2), 这个参数可以看下源码
### 3. 内容 content
POST http://localhost:31/test/content
Content-Type: application/json

{
  "url": "https://www.vipxs.la/56_56024/14383878.html",
  "config":
  {
    "novelMsgTileXR": "//[@id='info']/h1//text()",
    "novelMsgDescriptionXR": "//*[@id=\"intro\"]/p//text()",
    "novelMsgAuthXR": "//*[@id=\"info\"]/p[1]//text()",
    "novelCapterUrlListXR": "//*[@id=\"list\"]/dl//a//@href",
    "novelCapterNameXR": "//*[@id=\"wrapper\"]/div[5]/div[1]/div[2]/h1/regex('<h1>(正文)(.*)</h1>', 2)",
    "novelContentXR": "//[@id='content']"
  }
}

### //*[@id=\"wrapper\"]/div[5]/div[1]/div[2]/h1//text()/regex('^(正文)(.*?)$', 2)
### //[@id='info']/h1//text()/regex('^(正文)(.*?)$', 2)
### https://www.wenku8.net/book/2632.htm
### https://www.wenku8.net/book/1973.htm
### //div[@id='content']//tr[@align='center']//td//table//tbody//tr//td//span//b//@text()
### //div[@id='content']//tr[@align='center']//tr//td[1]//b//text()
