# src/main/resources/config/mqtt.properties
##################
#  MQTT 配置
##################
# 用户名
mqtt.username=c.c.
# 密码
mqtt.password=rootcccc
# 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
mqtt.url=tcp://8.146.199.165:1883
##################
#  MQTT 生产者
##################
# 连接服务器默认客户端ID
mqtt.producer.clientId=mqttProducer
# 默认的推送主题，实际可在调用接口时指定 topic1,test
mqtt.producer.defaultTopic=/test
##################
#  MQTT 消费者
##################
# 连接服务器默认客户端ID
mqtt.consumer.clientId=mqttConsumer
# 默认的接收主题，可以订阅多个Topic，逗号分隔
mqtt.consumer.defaultTopic=topic1
# 客户端2
mqtt.consumer.clientId2=mqttConsumer2
# 默认的接收主题，可以订阅多个Topic，逗号分隔
mqtt.consumer.defaultTopic2=/test