###
POST http://localhost:8002/login/u
Accept: application/json
Content-Type: application/json

{
  "name": "name",
  "pas": "pas"
}
### {"funcSet":["auth_2","auth_1"],"name":"name","pas":"pas"}

###
GET http://localhost:8002/open/
Accept: application/json
Content-Type: application/json
